### PR TITLE
Closes #58 fixed appendix

### LINKED ISSUE #58: So it create a link to the source code for the file above the citation.
So it create a link to the source code for the file above the citation.  

image

When we get a little more stable - we should start setting up the `renv.lock` as this will link to R environment.

_Originally posted by @bms63 in https://github.com/pharmaverse/blog/pull/56#discussion_r1244161660_

### PR DESCRIPTION
**Pull request by StefanThoma**
Thank you for your Pull Request! We have developed this task checklist to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your blog post.

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update), and make sure the corresponding issue is linked in the Development section on the right hand side
- [x] Run the script from `CICD.R` line by line to first check the spelling in your post and then to make sure your code is compatible with our code-style. Address any incongruences by following the instructions in the file! 
- [x] Choose (possibly several) `tag(s)` or categories from the current list: `c("Metadata", "SDTM", "ADaM", "TLG", "Shiny", "Community", "Conferences", "Submissions", "Technical")` for your blog post. If you cannot find anything that fits your blog post, add your own tag! We occasionally tidy up all `tags` for consistency.
- [x] Add a short description for your blog post in the `description` field at the top of the markdown document.
- [x] Blog post is *short*, *personalized*, *reproducible* and *readable*
- [x] Add a disclaimer at the top of your post, if appropriate (example: **Disclaimer** 
This blog contains opinions that are of the authors alone and do not necessarily reflect the strategy of their respective organizations.)
- [x] Address all merge conflicts and resolve appropriately
- [x] Assign two of us (@bms63, @manciniedoardo, @StefanThoma, @kaz462) as reviewers in the PR.
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by StefanThoma** [comment]
Still in draft, and was not able to re-knit everything, and only did it for one example so far. 
What do you think of this, @bms63?
The source link should take you now to the .qmd file responsible for the post, and the R environment should now take you to a .txt file on github that is automatically created and captures sessionInfo().

**Comment by StefanThoma** [comment]
Should we reconsider whether we want renv.lock files?

**Review by bms63 — COMMENTED** [review]
When the Quarto Publish job publishes it takes the latest CRAN package.  Will this get updated when that is run?

**Comment by StefanThoma** [comment]
> When the Quarto Publish job publishes it takes the latest CRAN package. Will this get updated when that is run?

AFAIK it will get updated whenever the qmd is rendered.

**Comment by bms63** [comment]
Cool!! Can you fix the actions and then we can merge in and see what it does!?!

**Comment by StefanThoma** [comment]
- add note about this to readme
- fix also other appendices
- fix template
- update quarto publisher?

**Comment by StefanThoma** [comment]
@bms63 I added a site to the blog including the session info. 
That way we don't need to transfer information from the gh-pages branch to main, but it is rendered nonetheless. 

Please feel free to render and check out the floating point post, thats where I adjusted the appendix function so far.

**Comment by bms63** [comment]
I had a chance to render the site locally - looks good.

Can you make a note of this process in the Readme and add a note for the reviewer to verify that this is in the blog post folder.

I don't really want to make this update across all the posts, unless you want to do it.  I only want to do this going forward.  Choose your adventure! :)  Thanks again.

**Comment by StefanThoma** [comment]
Hi @bms63 can we merge this into main so I can be sure that all the links work fine on the main branch? 
Only then would I like to update the template (I'd also update previous posts, I think)

**Comment by StefanThoma** [comment]
@bms63 not sure why this link does not work: 
https://rconsortium.shinyapps.io/submissions-pilot2/

**Review by bms63 — APPROVED** [review]
I like the reference to the session info - smart!

Why do we need the roxygen package?  

As an admin you can just bypass normal PR stuff if you are experimenting.  Just don't leave the site broken!!

**Pull request merged**
