### PR TITLE
Closes #189

### LINKED ISSUE #189: General Issue: "falcon" will be renamed as "cardinal"
### Background Information

The "falcon" repo has already been renamed as "cardinal". Following the merge of https://github.com/pharmaverse/cardinal/pull/223, the name change will be 💯 complete.

Please update all references of "falcon" to "cardinal".

### PR DESCRIPTION
**Pull request by telepath37**
Thank you for your Pull Request! We have developed this task checklist to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your blog post.

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update), and make sure the corresponding issue is linked in the Development section on the right hand side
- [x] Ensure your new post folder is of the form `"posts/zzz_DO_NOT_EDIT_<your post title>"`. This is so that the post date can be auto-updated upon the merge into `main`.
- [x] Run the script from `CICD.R` line by line to first check the spelling in your post and then to make sure your code is compatible with our code-style. Address any incongruences by following the instructions in the file! 
- [x] Choose (possibly several) `tag(s)` or categories from the current list: ` c("Metadata", "SDTM", "ADaM", "TLG", "Shiny", "Community", "Conferences", "Submissions", "Technical")` for your blog post. If you cannot find anything that fits your blog post, propose a new tag to the maintainers! Note: if you use a tag not from this list, the "Check Post Tags" CICD pipeline will error. We occasionally tidy up all `tags` for consistency.
- [x] Add a short description for your blog post in the `description` field at the top of the markdown document.
- [x] Blog post is *short*, *personalized*, *reproducible* and *readable*
- [x] Add a disclaimer at the top of your post, if appropriate (example: **Disclaimer** 
This blog contains opinions that are of the authors alone and do not necessarily reflect the strategy of their respective organizations.)
- [x] Address all merge conflicts and resolve appropriately
- [x] Assign two of us (@bms63, @manciniedoardo, @StefanThoma, @kaz462) as reviewers in the PR.
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by telepath37** [comment]
not sure what happens with the 'links failing'...it seems to come from other posts, which I didn't touch...

**Comment by StefanThoma** [comment]
Looks like the following links from other blogposts fail: 

### Errors in posts/2024-08-15_top_five_pharmaverse_packages/top-five-packages.md

* [404] [https://cran.r-project.org/web/packages/rtables/vignettes/introduction.html](https://cran.r-project.org/web/packages/rtables/vignettes/introduction.html) | Failed: Network error: Not Found

### Errors in posts/2024-07-24_working__groups_.../working__groups__updates.md

* [404] [https://advance.phuse.global/pages/viewpage.action?pageId=327777](https://advance.phuse.global/pages/viewpage.action?pageId=327777) | Failed: Network error: Not Found

### Errors in posts/2023-08-14_rhino_submission_2/rhino_submission_2.md

* [404] [https://www.r-consortium.org/announcement/2023/10/05/shiny-app-successfully-reviewed-by-fda-cder-staff-pilot-2-announcement-2](https://www.r-consortium.org/announcement/2023/10/05/shiny-app-successfully-reviewed-by-fda-cder-staff-pilot-2-announcement-2) | Failed: Network error: Not Found

I cannot access them either. 
@bms63 do you know what's going on?

**Comment by bms63** [comment]
Sadly things just break and urls don't re-direct.  If you can't easily find replacements then we can just let the links go through and see if they get fixed/fixed ourselves later.

**Comment by StefanThoma** [comment]
Links should get fixed in #238

**Review by StefanThoma — APPROVED** [review]
I think this looks good as an update. 
Generally, we suggest using the link package to add links to package mentions, but as this is an update to an existing post it is fine as is. 
Also, consider renaming the falcon.qmd file to cardinal.qmd. 
But I'll leave this up to you.

**Review by StefanThoma — APPROVED** [review]
LGTM!

**Comment by StefanThoma** [comment]
@bms63 can you approve this as well?

**Review by bms63 — CHANGES_REQUESTED** [review]
Could you change qmd file to cardinal. 

Is this going to be a package or more of catalog of TLFs??  If going to be package - any timelines on going to CRAN/already on CRAN?

Could we make the title a little more spicier? 

*  cardinal - collaborative effort to harmonize TLGs for clinical study reporting
*  cardinal - collaborative effort for clinical study reporting
*  cardinal - harmonize TLGs for clinical study reporting

**Comment by StefanThoma** [comment]
@bms63 should we just merge it in? It's an older post, so making the title spicier probably won't do much.

**Comment by bms63** [comment]
> @bms63 should we just merge it in? It's an older post, so making the title spicier probably won't do much.

He who controls the spice controls the universe

Sounds good please merge in

**Comment by StefanThoma** [comment]
Let's go! 
dune

**Pull request merged**
