### PR TITLE
Closes #52: remove signup

### LINKED ISSUE #52: Update Subscribe Email to Slack Channel
image

### PR DESCRIPTION
**Pull request by kaz462**
I simply removed the signup, or we can do following - let me know what you think

image

### CODE REVIEW

**Comment by kaz462** [comment]
not sure how to fix the current failing links, @StefanThoma @bms63 could you help check?

**Comment by bms63** [comment]
> not sure how to fix the current failing links, @StefanThoma @bms63 could you help check?

I think it doesn't like the slack link,  you can just add it to `.lycheeignore` and it won't check it.  It should work - this happens I think in admiral as well.

**Comment by kaz462** [comment]
Good to know. Thanks, @bms63 !

**Review by bms63 — APPROVED** [review]
Thanks!!!

**Pull request merged**
