### PR TITLE
Closes #94 PK Examples post

### LINKED ISSUE #94: Blog Post:  PK Examples on Pharmaverse
### Blog Post

 PK Examples on Pharmaverse

### PR DESCRIPTION
**Pull request by jeffreyad**

### CODE REVIEW

**Comment by rossfarrugia** [comment]
@jeffreyad blog looks good to me but can we hold off on posting this one til Jan please? First week when i'm back i just want to do some more testing on the Posit Cloud workspace and then happy for news to spread.

@bms63 @manciniedoardo looks like lots of links need updating in the past blogs now the `cran-release/` bit is gone from the admiral URLs. probably also worth letting the community know about this when you announce the 1.0 release as many will have saved bookmarks to their favourite pages.

**Comment by jeffreyad** [comment]
> @jeffreyad blog looks good to me but can we hold off on posting this one til Jan please? First week when i'm back i just want to do some more testing on the Posit Cloud workspace and then happy for news to spread.
> 
> @bms63 @manciniedoardo looks like lots of links need updating in the past blogs now the `cran-release/` bit is gone from the admiral URLs. probably also worth letting the community know about this when you announce the 1.0 release as many will have saved bookmarks to their favourite pages.

@rossfarrugia sounds fine to me, thanks!

**Review by rossfarrugia — APPROVED** [review]
fine for me now once conflicts resolved

**Comment by rossfarrugia** [comment]
@bms63 any time is fine for me. Jeff helped test the posit workspace for me. Planning to do a comms about it later in the week on pharmaverse slack around a f2f meet i have this week.

**Pull request merged**
