### PR TITLE
Add `blog` Docker image 

### LINKED ISSUE #118: General Issue: Experimenting with Docker Image for Contributor
### Background Information
Currently, when users want to contribute or create a post in the repository, they must install all R package dependencies that the repository requires before the contributor blog page can be rendered.

Related issue: https://github.com/pharmaverse/blog/issues/108

This could hinder the user's ability to move quickly and may potentially pollute their local environment. Users should be able to contribute to the repository without having to install all dependencies.

### Proposal
My proposal is to create a Docker image with all the dependencies installed and push this to the registry. 
Users can pull and use the image for development before pushing commits to the repository.

### PR DESCRIPTION
**Pull request by donyunardi**
Fixes #118 

* Add Dockerfile to the repo
* Update README.md for instruction on how to use the `blog` image.

Image pushed to registry:
https://github.com/pharmaverse/blog/pkgs/container/blog

### CODE REVIEW

**Comment by donyunardi** [comment]
I'm unsure why the `Links` pipeline failed. The URLs in question appear to be correct to me. 🤷🏼 
Let me know and I'll fix it.

**Comment by bms63** [comment]
The SO link has been popping up for the last week.  It is still live when I use the bad link to go visit the site.  We can just ignore unless you see something quick we can do to fix it.

The docker image stuff is very cool.  thank for putting it together.

**Comment by donyunardi** [comment]
I added links to ignore to .lycheeignore:
* localhost
* links to registry (because this requires github token)

I think this PR is ready to merge but would love to have someone test the instruction in the README.
Can we leverage our pharmaverse community to test this?

**Comment by donyunardi** [comment]
Adding stackoverflow too because the we got forbidden error. 

@bms63 links are all good now.

**Comment by bms63** [comment]
@StefanThoma has offered to test out!!  We might want to get someone from outside roche to test as well.  I can do later this week.

**Comment by donyunardi** [comment]
Thanks for reviewing this @StefanThoma 

It turns out, the image visibility was private before. I updated this and make it public. 
Can you try again?

**Comment by donyunardi** [comment]
Thanks @StefanThoma 
I added clarity on the git activity here: fcb2df0d3b469137f232868f1eedf442a746fad3

**Comment by bms63** [comment]
Hey all,

Sorry I haven't been able to catch up on this.  @StefanThoma is this good to merge?  feel free to merge in if so! Thanks again @donyunardi !!  Looking forward to more nest/teal posts as we have way too much ADaM domination!! :)

**Review by StefanThoma — APPROVED** [review]
LGTM!!

**Pull request merged**
