### PR TITLE
added google analytics tag

### PR DESCRIPTION
**Pull request by gigikenneth**
Thank you for your Pull Request! We have developed this task checklist to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your blog post.

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update), and make sure the corresponding issue is linked in the Development section on the right hand side
- [ ] Run the script from `CICD.R` line by line to first check the spelling in your post and then to make sure your code is compatible with our code-style. Address any incongruences by following the instructions in the file! 
- [ ] Choose (possibly several) `tag(s)` or categories from the current list: `c("Metadata", "SDTM", "ADaM", "TLG", "Shiny", "Community", "Conferences", "Submissions", "Technical")` for your blog post. If you cannot find anything that fits your blog post, add your own tag! We occasionally tidy up all `tags` for consistency.
- [ ] Add a short description for your blog post in the `description` field at the top of the markdown document.
- [ ] Blog post is *short*, *personalized*, *reproducible* and *readable*
- [ ] Add a disclaimer at the top of your post, if appropriate (example: **Disclaimer** 
This blog contains opinions that are of the authors alone and do not necessarily reflect the strategy of their respective organizations.)
- [ ] Address all merge conflicts and resolve appropriately
- [ ] Assign two of us (@bms63, @manciniedoardo, @StefanThoma, @kaz462) as reviewers in the PR.
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Review by bms63 — COMMENTED** [review]
Could we put some guidance in the readme with how/where to access the analytics?  I have never looked at something like this before.

**Comment by manciniedoardo** [comment]
Thanks @gigikenneth, to view the analytics is it as simple as just going to the analytics link that was emailed to us?

**Comment by gigikenneth** [comment]
> Thanks @gigikenneth, to view the analytics is it as simple as just going to the analytics link that was emailed to us?

Hi @manciniedoardo , exactly. After the pull request is merged, the numbers will go to Google Analytics and you can view it using the link you received. Other people can be added to Google Analytics as Viewers/Editors.

If we want the numbers to be open and accessible to anyone, then we'd have to make a dashboard, but that's probably overkill since we're about to start.

**Comment by manciniedoardo** [comment]
> > Thanks @gigikenneth, to view the analytics is it as simple as just going to the analytics link that was emailed to us?
> 
> Hi @manciniedoardo , exactly. After the pull request is merged, the numbers will go to Google Analytics and you can view it using the link you received. Other people can be added to Google Analytics as Viewers/Editors.
> 
> If we want the numbers to be open and accessible to anyone, then we'd have to make a dashboard, but that's probably overkill since we're about to start.

Happy to keep it as simple as possible, I don't think everyone needs access.

**Comment by StefanThoma** [comment]
Will we need a banner at the bottom informing the users about this, and asking for permission?
I think there may be some EU regulations regarding that.

**Comment by StefanThoma** [comment]
> Will we need a banner at the bottom informing the users about this, and asking for permission? I think there may be some EU regulations regarding that.

hmmm: 
https://chatgpt.com/share/39144168-069d-412d-ab3e-ced277905a76

**Comment by gigikenneth** [comment]
@StefanThoma , thank you for sharing, and yes, I agree we needed to ask for consent before proceeding. I'm looking at how we can do it in Quarto 👀

**Comment by StefanThoma** [comment]
> @StefanThoma , thank you for sharing, and yes, I agree we needed to ask for consent before proceeding. I'm looking at how we can do it in Quarto 👀

I just asked GPT again, looks like it's possible: 
https://chatgpt.com/share/223430c3-c804-4145-858b-f87b18de3217

**Review by manciniedoardo — APPROVED** [review]

**Pull request merged**
