### PR TITLE
Rhino fda submission 2

### PR DESCRIPTION
**Pull request by IsmaelRdz25**
Hi,

We've created this blog post draft for one of the topics we discussed previously. Please take a look and let me know if you like it! 

Let's confirm the date when it will be published.

Thanks!!
Ismael Rdz

### CODE REVIEW

**Review by rossfarrugia — CHANGES_REQUESTED** [review]
I discussed with Ismael on Slack and his team will submit Rhino for pharmaverse inclusion before this blog gets approved and posted to the blog site, so please consider this PR on hold for now.

**Comment by bms63** [comment]
Yay!! this is very exciting!!

**Comment by IsmaelRdz25** [comment]
@rossfarrugia have you completed the post review? It was already reviewed by our marketing team. Thanks!

**Review by rossfarrugia — APPROVED** [review]
Fine for me @IsmaelRdz25! will leave @bms63 @manciniedoardo or @kaz462 to merge this if they're happy.

**Comment by bms63** [comment]
i will look over ASAP.  apologies for delay

**Comment by bms63** [comment]
Just FYI - In Pilot 3 we don't use the `pkglite` as FDA said `.zip` and `.r` files are totally fine to submit now.  Paul (FDA reviewer) said this was a misunderstanding in pilot 1.

Perhaps we can discuss in Working Group meeting this week? 
image

**Comment by bms63** [comment]
Could we get a little blurb about rhino also being on the pharmaverse??

**Comment by bms63** [comment]
Perhaps this could be an optional expansion window.  It is quite big and takes away from the flow of the article 

image

**Comment by bms63** [comment]
There is a file in `R/CICD.R` to help with the styler and spell checkers.

**Comment by bms63** [comment]
ohhh could that video demo of the app get embedded in the article?  that looks way cool!!

**Comment by IsmaelRdz25** [comment]
Hello, Thank you for all your comments. I'm off the next two days and I'll get back to them on Monday. 

Could you send me an invite for the Working Group Meeting?

**Comment by bms63** [comment]
Can you DM me your email on slack and I can forward you the invite.

Also - Pilot 2 is succsessfully completed so we should mention that in this post

**Comment by IsmaelRdz25** [comment]
My company email is: ismael.rodriguez@appsilon.com

I'll write that part on the blog post about the Pilot 2.

**Comment by IsmaelRdz25** [comment]
I've made all additions to the text (FDA-Pilot-App button + Video). Also, corrected style. Post is ready now for second review.

**Pull request merged**
